# Library name that this app depends on
LIBRARY_NAMES = \
 bus \
 common \
 drv \
 hc

# Include default make config
include $(PROJBASEDIR)/src/config.mk

# Include default make rules
include $(PROJBASEDIR)/src/rules.mk
