# Library name that this app depends on
LIBRARY_NAMES = \
 bus \
 common \
 drv \
 hc

# Include default make config
include $(PROJBASEDIR)/src/config.gmk

# Include default make rules
include $(PROJBASEDIR)/src/rules.gmk
