# Library files to link against
LINKLIBS = \
 common \
 hc

# Include default make config
include $(PROJBASEDIR)/src/DefaultConfig

# Include default make rules
include $(PROJBASEDIR)/src/DefaultRules
